name: Build and deploy Node.js app to Azure Web App - c5imdcapp

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      # ✅ Install and build frontend with .env.production
      - name: Install and build frontend
        run: |
          cd frontend
          npm install
          npm run build

      # ✅ Install backend dependencies
      - name: Install backend dependencies
        working-directory: backend
        run: |
          npm install
          npm run start

      # ✅ Copy frontend build output to backend
      - name: Copy frontend dist to backend folder
        run: cp -r frontend/dist backend/

      # ✅ Zip backend folder for deployment
      - name: Zip artifact for deployment
        working-directory: ./backend
        run: |
          zip -r release.zip .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: backend/release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact
        run: unzip release.zip

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'c5imdcapp'
          slot-name: 'Production'
          package: .
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_8F5465B8B35B489F9462A4B1FB4E19BA }}
