name: Build and deploy Node.js app to Azure Web App - c5imdcapp

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      # 🔧 Install and build frontend
      - name: Install and build frontend
        working-directory: frontend
        run: |
          npm install
          npm run build

      # 🔧 Install backend
      - name: Install backend dependencies
        working-directory: backend
        run: |
          npm install

      # 🗜️ Zip entire backend (including frontend/build inside it)
      - name: Copy frontend dist to backend folder
        run: cp -r frontend/dist backend/

      - name: Zip artifact for deployment
        working-directory: ./backend
        run: |
          zip -r release.zip .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: backend/release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact
        run: unzip release.zip

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'c5imdcapp'
          slot-name: 'Production'
          package: .
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_A090FF9091E14C14A5A71DE75C6A741E  }}
